# Generated by Django 5.2.5 on 2025-08-20 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CyberPal', help_text="Your pet's name - users cajn customize this later", max_length=50)),
                ('pet_type', models.CharField(choices=[('cat', 'Cyber Cat'), ('dog', 'Cyber Dog'), ('dragon', 'Cyber Dragon'), ('robot', 'Cyber Robot')], default='cat', max_length=20)),
                ('current_mood', models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('worried', 'Worried'), ('sad', 'Sad'), ('excited', 'Excited')], default='neutral', max_length=20)),
                ('mood_score', models.IntegerField(default=50, help_text='Internal score used to calculate mood (0 = very sad, 100 = very happy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cyber_pet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=20)),
                ('mood_score', models.IntegerField()),
                ('trigger_action', models.CharField(blank=True, help_text='What security action caused this mood?', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_history', to='pet.pet')),
            ],
            options={
                'verbose_name_plural': 'Mood Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
