# Generated by Django 5.2.5 on 2025-08-20 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strenght_score', models.IntegerField(help_text='Password strenght from 0-100')),
                ('has_uppercase', models.BooleanField(default=False)),
                ('has_lowercase', models.BooleanField(default=False)),
                ('has_numbers', models.BooleanField(default=False)),
                ('has_symbols', models.BooleanField(default=False)),
                ('lenght', models.IntegerField()),
                ('is_unique', models.BooleanField(default=True, help_text='Is this a unique password or reused from another account?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BreachCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_checked', models.EmailField(help_text='Which email address was checked (we hash this for privacy)', max_length=254)),
                ('breaches_found', models.IntegerField(default=0, help_text='Number of data breaches this email was found in')),
                ('breach_details', models.JSONField(blank=True, default=list, help_text='Details afbout each breach (from HAVEIBEENPwnedAPI)')),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_checked'],
                'unique_together': {('user', 'email_checked')},
            },
        ),
        migrations.CreateModel(
            name='SecurityAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('password_check_strong', 'Checked Password - Strong'), ('password_check_weak', 'Checked Password - Weak'), ('password_updated', 'Updated Password'), ('breach_check_clean', 'Email Breach Check - Clean'), ('breach_found', 'Email Breach Found'), ('2fa_enabled', 'Enabled 2FA'), ('2fa_disabled', 'Disabled 2FA'), ('security_tip_viewed', 'Viewed Security Tip'), ('security_scan_completed', 'Completed Security Scan')], help_text='What specific security action was performed?', max_length=30)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Extra data like password strength score, breach details, etc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='security_se_user_id_5eb6d7_idx')],
            },
        ),
    ]
