# Generated by Django 5.2.5 on 2025-08-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordcheck',
            name='strenght_score',
        ),
        migrations.AddField(
            model_name='passwordcheck',
            name='strength_score',
            field=models.IntegerField(default=0, help_text='Password strength from 0-100'),
        ),
    ]
