# Generated by Django 5.2.5 on 2025-08-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_remove_passwordcheck_strenght_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordcheck',
            old_name='lenght',
            new_name='length',
        ),
        migrations.AlterField(
            model_name='passwordcheck',
            name='strength_score',
            field=models.IntegerField(help_text='Password strength from 0-100'),
        ),
    ]
