# Generated by Django 5.2.5 on 2025-08-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_rename_lenght_passwordcheck_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordcheck',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
