# Generated by Django 5.2.5 on 2025-08-20 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Send email alerts for security issues?')),
                ('weekly_reports', models.BooleanField(default=True, help_text='Send weekly security summary emails?')),
                ('pet_name_customized', models.BooleanField(default=False, help_text="Has the user customized their pet's name?")),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Has user enabled 2FA on their account?')),
                ('last_breach_check', models.DateTimeField(blank=True, help_text='When did user last check for email breaches?', null=True)),
                ('total_security_score', models.IntegerField(default=0, help_text='Overall security score (for gamification)')),
                ('streak_days', models.IntegerField(default=0, help_text='Overall security score (for gamification)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
