# Generated by Django 5.2.5 on 2025-08-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_password_check',
            field=models.DateTimeField(blank=True, help_text='When did user last check for email breaches?', null=True),
        ),
    ]
